# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/com-pas/*
    username: OWNER
    password: ${{ secrets.DB_GITHUB_PACKAGES }}

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
      # Next dependencies will be ignored, because they should stay in sync with the 'eclipse.aggr' versions.
      - dependency-name: org.eclipse.core:org.eclipse.core.resources
      - dependency-name: org.eclipse.emf:org.eclipse.emf.ecore
      - dependency-name: org.eclipse.emf:org.eclipse.emf.common
      - dependency-name: org.eclipse.ocl:org.eclipse.ocl.pivot
      - dependency-name: org.eclipse.ocl:org.eclipse.ocl.xtext.completeocl
      - dependency-name: org.eclipse.ocl:org.eclipse.ocl.xtext.oclstdlib
      - dependency-name: org.antlr.runtime:org.antlr.runtime

  - package-ecosystem: "docker"
    directory: "/app/src/main/docker/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
